framework:
    translator: ~
    templating: { engines: [twig] }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "noreply@coursesource.com"
        sender_name: "Coursesource mail service"